spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        name: dev
        username: sa
        password: sa
        hikari:
                    data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        persistenceUnitName: DEV-RBO
        properties:
            hibernate.generate_statistics: "true"
            hibernate.use_sql_comments: "true"
            hibernate.format_sql: "true"
            hibernate.show_sql: "true"
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data

    thymeleaf:
         cache: "false"

loggining:
    level.: "DEBUG"

server:
    port: 8081

